import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";
import AuthContextProvider from "../../context/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await auth();

  // console.log(session.user.email);

  return (
    <SessionProvider session={session}>
      <AuthContextProvider session={session ? session : null}>
        <html lang="en">
          <body className={`${inter.className}`}>
            <Header />
            <div className="margin-b">
              {children}
            </div>

            <Footer />

          </body>
        </html>
      </AuthContextProvider>
    </SessionProvider>
  );
}
